[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/health"
healthcheckTimeout = 100

[deploy.env]
PORT = "10000"
PYTHON_VERSION = "3.10.0" 