services:
  - type: web
    name: farmtech-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000
    plan: starter  # Using starter plan for more RAM
    disk:
      name: model-storage
      mountPath: /opt/render/model-storage
      sizeGB: 1
